apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-app
 namespace: python-app
 labels:
  app: python-app
spec:
 replicas: 2
 selector:
  matchLabels:
    app: python-app
 template:
  metadata:
    labels:
      app: python-app
  spec:
    imagePullSecrets:
    - name: my-registry-key
    containers:
    - name: python-app
      image: asruiz1235/python-app:10 
      ports:
      - containerPort: 5000
