apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pod
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: ejemplo-servicio
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
